# Mapeo de números a nombres de equipos
teams_mapping = {
    3: "argentinos",
    33: "instituto",
    25: "atletico_tucuman",
    13: "lanus",
    5: "banfield",
    14: "newells",
    82: "barracas",
    45: "platense",
    26: "belgrano",
    17: "racing",
    6: "boca_juniors",
    123: "riestra",
    78: "central_cordoba",
    18: "river_plate",
    29: "defensa",
    35: "rosario_central",
    8: "estudiantes",
    19: "san_lorenzo",
    9: "gimnasia",
    81: "sarmiento",
    10: "godoy_cruz",
    52: "talleres",
    11: "huracan",
    20: "tigre",
    32: "independiente_rivadavia",
    39: "union",
    12: "independiente",
    21: "velez"
}
